# Generated by Django 4.2 on 2023-04-14 14:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("wireguard", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="wireguardserver",
            name="enabled",
            field=models.BooleanField(default=True, verbose_name="Enable this server"),
        ),
    ]
