# Generated by Django 4.2 on 2023-04-14 22:45

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("wireguard", "0003_passwordreset"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="wireguardclient",
            unique_together={("server", "name")},
        ),
    ]
