# Generated by Django 4.2 on 2023-04-14 23:08

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("wireguard", "0004_alter_wireguardclient_unique_together"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="wireguardclient",
            options={"ordering": ("server", "name")},
        ),
        migrations.AlterModelOptions(
            name="wireguardserver",
            options={"ordering": ("name", "interface_name", "enabled")},
        ),
    ]
