# Generated by Django 4.2 on 2023-04-17 13:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("wireguard", "0006_serveraccess"),
    ]

    operations = [
        migrations.AlterField(
            model_name="serveraccess",
            name="server",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="invites", to="wireguard.wireguardserver"
            ),
        ),
    ]
