# Generated by Django 4.2 on 2023-04-21 20:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("wireguard", "0006_serveraccess"),
    ]

    operations = [
        migrations.AddField(
            model_name="wireguardclient",
            name="allow_direct_peering",
            field=models.BooleanField(default=False, verbose_name="Allow direct communication with this client"),
        ),
        migrations.AddField(
            model_name="wireguardserver",
            name="allow_direct_peering",
            field=models.BooleanField(default=True, verbose_name="Allow client peer2peer communication"),
        ),
        migrations.AlterField(
            model_name="serveraccess",
            name="server",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="invites", to="wireguard.wireguardserver"
            ),
        ),
        migrations.CreateModel(
            name="WireguardClientLocalNetwork",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("ip", models.GenericIPAddressField(unpack_ipv4=True, verbose_name="IP Address")),
                ("cidr_mask", models.IntegerField(default=None, null=True, verbose_name="Network mask (CIDR)")),
                ("gateway", models.GenericIPAddressField(unpack_ipv4=True, verbose_name="Gateway IP Address")),
                ("public_ip", models.GenericIPAddressField(unpack_ipv4=True, verbose_name="Public IP Address")),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="local_networks",
                        to="wireguard.wireguardclient",
                    ),
                ),
            ],
            options={
                "verbose_name": "Local Network",
                "verbose_name_plural": "Local Networks",
            },
        ),
        migrations.AlterModelOptions(
            name="wireguardclientnetworks",
            options={"verbose_name": "Bridged Network", "verbose_name_plural": "Bridged Networks"},
        ),
    ]
