# Generated by Django 4.2 on 2023-04-21 22:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("wireguard", "0008_remove_wireguardclient_preshared_key_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="wireguardclient",
            name="public_key",
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name="Public key"),
        ),
    ]
