# Generated by Django 4.2 on 2023-04-21 22:17

from django.db import migrations

from wireguard.utils import public_key_from_private


def convert_public_keys(apps, schema_editor):
    WireguardClient = apps.get_model("wireguard", "WireguardClient")
    for client in WireguardClient.objects.all():
        client.public_key = public_key_from_private(client.private_key)
        client.save()


class Migration(migrations.Migration):
    dependencies = [
        ("wireguard", "0009_wireguardclient_public_key"),
    ]

    operations = [migrations.RunPython(convert_public_keys)]
